heat_template_version: 2016-04-08


description: >
  A network service (NS) representing a PRE group instance

parameters:


  management_provider_network:
    type: string
    description: Name or ID of the provider network use for management network Floating IPs.

  subscriber_provider_network:
    type: string
    description: Name or ID of the provider network use for subscriber network Floating IPs.


#  dns_domain:
#    type: string
#    description: Name of DNS domain to use for Floating IP networks.

  client_network:
    type: string

  server_network:
    type: string

  maximum_pre_count:
    type: number

  pre_count:
    type: number

  cik:
    type: string

resources:

#
#  General Networks
#

  networks:
    type: packetlogic::standard_networks::ns
    properties:
      management_provider_network: { get_param: management_provider_network }
      subscriber_provider_network: { get_param: subscriber_provider_network }
#      dns_domain: { get_param: dns_domain }


#
#  General VNFs
#

  lm_vnf:
    type: packetlogic::lm::vnf
    properties:
      management_network: { get_attr: [networks,management_net] }
      management_provider_network: { get_param: management_provider_network }
##      dns_domain: { get_param: dns_domain }
      service_network: { get_attr: [networks,service_net] }
      cik: { get_param: cik }


#
#  PREs
#





  pre_group:
    type: packetlogic::pre_group::ns
    properties:
      name: preg
##      dns_domain: { get_param: dns_domain }
      management_provider_network: { get_param: management_provider_network }
      management_network: { get_attr: [networks,management_net] }
      service_network: { get_attr: [networks,service_net] }
      qsync_network: { get_attr: [networks,qsync_net] }
      flowsync_network: { get_attr: [networks,flowsync_net] }
      pre_count: { get_param: pre_count }
      maximum_pre_count: { get_param: maximum_pre_count }
      client_network: { get_param: client_network }
      server_network: { get_param: server_network }



