   "packetlogic::contrail_networks::channel":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/contrail_networks_ns/contrail_channel.yaml
   "packetlogic::contrail_networks::ns":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/contrail_networks_ns/nsd.yaml
   "packetlogic::sysmgr::vnf":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/sysmgr_vnf/vnfd.yaml
   "packetlogic::frigg::vnf":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/frigg_vnf/vnfd.yaml
   "packetlogic::environment::ns":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/environment_ns/nsd.yaml
   "packetlogic::internal_networks::ns":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/internal_networks_ns/nsd.yaml
   "packetlogic::standard_networks::ns":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/standard_networks_ns/nsd.yaml
   "packetlogic::pic::vnf":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/pic_vnf/vnfd.yaml
   "packetlogic::psm::vnf":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/psm_vnf/vnfd.yaml
   "packetlogic::channel_networks::channel":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/channel_networks_ns/channel.yaml
   "packetlogic::channel_networks::ns":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/channel_networks_ns/nsd.yaml
   "packetlogic::single_pre::vnf":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/single_pre_vnf/vnfd.yaml
   "packetlogic::pre::vnf":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/pre_vnf/vnfd.yaml
   "packetlogic::pre::vnfc":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/pre_vnf/vnfc.yaml
   "packetlogic::pre::channel_ports":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/pre_vnf/channel_ports.yaml
   "packetlogic::pre::channel_port":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/pre_vnf/channel_port.yaml
   "packetlogic::pre::vnf_indexed":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/pre_vnf/vnfd_indexed.yaml
   "packetlogic::pre::vnf_contrail":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/pre_vnf/vnfd_contrail.yaml
   "packetlogic::pre_scaling::ns":    REPOSITORY_URL_PREFIX/rel2-alpha/heat/19.0.0.5/pre_vnf/pre_scaling_ns.yaml
