heat_template_version: 2016-04-08


description: >
  A network service (NS) representing a complete PL system

parameters:

  management_provider_network:
    type: string
    description: Name or ID of the provider network use for management network Floating IPs.

  subscriber_provider_network:
    type: string
    description: Name or ID of the provider network use for subscriber network Floating IPs.

  data_image:
    type: string
    description: Name of image that holds initial system data.

  key_name:
    type: string
    description: Name of key for admin


resources:

#
#  General Networks
#

  networks:
    type: packetlogic::standard_networks::ns
    properties:
      management_provider_network: { get_param: management_provider_network }
      subscriber_provider_network: { get_param: subscriber_provider_network }
      ns_instance_name: { get_param: "OS::stack_name" }


#
#  General VNFs
#

  sysmgr_vnf:
    type: packetlogic::sysmgr::vnf
    properties:
      management_network: { get_attr: [networks,management_net] }
      management_provider_network: { get_param: management_provider_network }
      service_network: { get_attr: [networks,service_net] }
      data_image:  { get_param: data_image }
      ns_instance_name: {get_param: "OS::stack_name"}
      ns_vnf_instance_name: sysmgr_1
      key_name: { get_param: key_name }
      scaling:
        - { get_attr: [frigg_vnf, scalingdata] }


  psm_vnf:
    type: packetlogic::psm::vnf
    properties:
      management_network: { get_attr: [networks,management_net] }
      service_network: { get_attr: [networks,service_net] }
      subscriber_network: { get_attr: [networks,subscriber_net] }
      management_provider_network: { get_param: management_provider_network }
      subscriber_provider_network: { get_param: subscriber_provider_network }
      ns_vnf_instance_name: psm_1
      ns_instance_name: {get_param: "OS::stack_name"}

  pic_vnf:
    type: packetlogic::pic::vnf
    properties:
      management_network: { get_attr: [networks,management_net] }
      service_network: { get_attr: [networks,service_net] }
      management_provider_network: { get_param: management_provider_network }
      ns_vnf_instance_name: pic_1
      ns_instance_name: {get_param: "OS::stack_name"}



#
#  PRE cluster VNF
#


  frigg_vnf:
    type: packetlogic::frigg::vnf
    depends_on:
      - source_subnet
      - destination_subnet
    properties:
      management_network: { get_attr: [networks,management_net] }
      service_network: { get_attr: [networks,service_net] }
      qsync_network: { get_attr: [networks,qsync_net] }
      flowsync_network: { get_attr: [networks,flowsync_net] }
      management_provider_network: { get_param: management_provider_network }
      int_network: { get_resource: source_net }
      ext_network: { get_resource: destination_net }
      ns_instance_name: {get_param: "OS::stack_name"}
      ns_vnf_instance_name: frigg_1
      key_name: { get_param: key_name }
      desired_count: 4


  source_net:
    type: OS::Neutron::Net
    properties:
      name: source-net
      port_security_enabled: false

  source_subnet:    
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: source_net }
      cidr: 192.168.140.0/24

  destination_net:
    type: OS::Neutron::Net
    properties:
      name: destination-net
      port_security_enabled: false

  destination_subnet:    
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: destination_net }
      cidr: 192.168.140.0/24